In [2]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# importation du fichier table 1

In [3]:
df=pd.read_excel('table.xlsx')

In [4]:
print(df)

df.info()

                                            Unnamed: 0      Unnamed: 1  \
0                            1 Human development index             NaN
1                                                  NaN             NaN
2                                                  NaN             NaN
3                                                  NaN             NaN
4                     Table 1. Human development index             NaN
5                                                  NaN             NaN
6                                                  NaN             NaN
7                                            HDI ranka             NaN
8                                                  NaN             NaN
9                               HIGH HUMAN DEVELOPMENT             NaN
10                                                   1         Iceland
11                                                   2          Norway
12                                                   3       Australia
13                                                   4          Canada
14                                                   5         Ireland
15                                                   6          Sweden
16                                                   7     Switzerland
17                                                   8           Japan
18                                                   9     Netherlands
19                                                  10          France
20                                                  11         Finland
21                                                  12   United States
22                                                  13           Spain
23                                                  14         Denmark
24                                                  15         Austria
25                                                  16  United Kingdom
26                                                  17         Belgium
27                                                  18      Luxembourg
28                                                  19     New Zealand
29                                                  20           Italy
..                                                 ...             ...
190                               Developing countries             NaN
191                          Least developed countries             NaN
192                                        Arab States             NaN
193                          East Asia and the Pacific             NaN
194                    Latin America and the Caribbean             NaN
195                                         South Asia             NaN
196                                 Sub-Saharan Africa             NaN
197             Central and Eastern Europe and the CIS             NaN
198                                               OECD             NaN
199                                   High-income OECD             NaN
200                                                NaN             NaN
201                             High human development             NaN
202                           Medium human development             NaN
203                              Low human development             NaN
204                                                NaN             NaN
205                                        High income             NaN
206                                      Middle income             NaN
207                                         Low income             NaN
208                                                NaN             NaN
209                                              World             NaN
210                                                NaN             NaN
211                                                NaN             NaN
212                                                NaN             NaN
213                                                NaN             NaN
214                                                NaN             NaN
215                                              NOTES             NaN
216                                                NaN             NaN
217  a. The HDI rank is determined using HDI values...             NaN
218                                                NaN             NaN
219  SOURCES\nColumn 1: calculated on the basis of ...             NaN

     Unnamed: 2  \
0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
5           NaN
6           NaN
7           NaN
8           NaN
9           NaN
10          NaN
11          NaN
12          NaN
13          NaN
14          NaN
15          NaN
16          NaN
17          NaN
18          NaN
19          NaN
20          NaN
21          NaN
22          NaN
23          NaN
24          NaN
25          NaN
26          NaN
27          NaN
28          NaN
29          NaN
..          ...
190         NaN
191         NaN
192         NaN
193         NaN
194         NaN
195         NaN
196         NaN
197         NaN
198         NaN
199         NaN
200         NaN
201         NaN
202         NaN
203         NaN
204         NaN
205         NaN
206         NaN
207         NaN
208         NaN
209         NaN
210         NaN
211         NaN
212         NaN
213         NaN
214         NaN
215         NaN
216         NaN
217         NaN
218         NaN
219         NaN

    Monitoring human development: enlarging people's choices . . .  \
0                                                  NaN
1                                                  NaN
2                                                  NaN
3                                                  NaN
4                                                  NaN
5                                                  NaN
6            Human development index (HDI) value\n2005
7                                                  NaN
8                                                  NaN
9                                                  NaN
10                                               0.968
11                                               0.968
12                                               0.962
13                                               0.961
14                                               0.959
15                                               0.956
16                                               0.955
17                                               0.953
18                                               0.953
19                                               0.952
20                                               0.952
21                                               0.951
22                                               0.949
23                                               0.949
24                                               0.948
25                                               0.946
26                                               0.946
27                                               0.944
28                                               0.943
29                                               0.941
..                                                 ...
190                                              0.691
191                                              0.488
192                                              0.699
193                                              0.771
194                                              0.803
195                                              0.611
196                                              0.493
197                                              0.808
198                                              0.916
199                                              0.947
200                                                NaN
201                                              0.897
202                                              0.698
203                                              0.436
204                                                NaN
205                                              0.936
206                                              0.776
207                                              0.570
208                                                NaN
209                                              0.743
210                                                NaN
211                                                NaN
212                                                NaN
213                                                NaN
214                                                NaN
215                                                NaN
216                                                NaN
217                                                NaN
218                                                NaN
219                                                NaN

     Unnamed: 4                               Unnamed: 5 Unnamed: 6  \
0           NaN                                      NaN        NaN
1           NaN                                      NaN        NaN
2           NaN                                      NaN        NaN
3           NaN                                      NaN        NaN
4           NaN                                      NaN        NaN
5           NaN                                      NaN        NaN
6           NaN  Life expectancy at birth\n(years)\n2005        NaN
7           NaN                                      NaN        NaN
8           NaN                                      NaN        NaN
9           NaN                                      NaN        NaN
10          NaN                                     81.5        NaN
11          NaN                                     79.8        NaN
12          NaN                                     80.9        NaN
13          NaN                                     80.3        NaN
14          NaN                                     78.4        NaN
15          NaN                                     80.5        NaN
16          NaN                                     81.3        NaN
17          NaN                                     82.3        NaN
18          NaN                                     79.2        NaN
19          NaN                                     80.2        NaN
20          NaN                                     78.9        NaN
21          NaN                                     77.9        NaN
22          NaN                                     80.5        NaN
23          NaN                                     77.9        NaN
24          NaN                                     79.4        NaN
25          NaN                                     79.0        NaN
26          NaN                                     78.8        NaN
27          NaN                                     78.4        NaN
28          NaN                                     79.8        NaN
29          NaN                                     80.3        NaN
..          ...                                      ...        ...
190         NaN                                     66.1        NaN
191         NaN                                     54.5        NaN
192         NaN                                     67.5        NaN
193         NaN                                     71.7        NaN
194         NaN                                     72.8        NaN
195         NaN                                     63.8        NaN
196         NaN                                     49.6        NaN
197         NaN                                     68.6        NaN
198         NaN                                     78.3        NaN
199         NaN                                     79.4        NaN
200         NaN                                      NaN        NaN
201         NaN                                     76.2        NaN
202         NaN                                     67.5        NaN
203         NaN                                     48.5        NaN
204         NaN                                      NaN        NaN
205         NaN                                     79.2        NaN
206         NaN                                     70.9        NaN
207         NaN                                     60.0        NaN
208         NaN                                      NaN        NaN
209         NaN                                     68.1        NaN
210         NaN                                      NaN        NaN
211         NaN                                      NaN        NaN
212         NaN                                      NaN        NaN
213         NaN                                      NaN        NaN
214         NaN                                      NaN        NaN
215         NaN                                      NaN        NaN
216         NaN                                      NaN        NaN
217         NaN                                      NaN        NaN
218         NaN                                      NaN        NaN
219         NaN                                      NaN        NaN

                                            Unnamed: 7 Unnamed: 8  \
0                                                  NaN        NaN
1                                                  NaN        NaN
2                                                  NaN        NaN
3                                                  NaN        NaN
4                                                  NaN        NaN
5                                                  NaN        NaN
6    Adult literacy rate\n(% aged 15 and above)\n19...        NaN
7                                                  NaN        NaN
8                                                  NaN        NaN
9                                                  NaN        NaN
10                                                  ..          d
11                                                  ..          d
12                                                  ..          d
13                                                  ..          d
14                                                  ..          d
15                                                  ..          d
16                                                  ..          d
17                                                  ..          d
18                                                  ..          d
19                                                  ..          d
20                                                  ..          d
21                                                  ..          d
22                                                  ..          d
23                                                  ..          d
24                                                  ..          d
25                                                  ..          d
26                                                  ..          d
27                                                  ..          d
28                                                  ..          d
29                                                98.4        NaN
..                                                 ...        ...
190                                               76.6        NaN
191                                               53.9        NaN
192                                               70.3        NaN
193                                               90.7        NaN
194                                               90.3        NaN
195                                               59.5        NaN
196                                               60.3        NaN
197                                               99.0        NaN
198                                                 ..        NaN
199                                                 ..        NaN
200                                                NaN        NaN
201                                                 ..        NaN
202                                               78.0        NaN
203                                               54.4        NaN
204                                                NaN        NaN
205                                                 ..        NaN
206                                               89.9        NaN
207                                               60.2        NaN
208                                                NaN        NaN
209                                               78.6        NaN
210                                                NaN        NaN
211                                                NaN        NaN
212                                                NaN        NaN
213                                                NaN        NaN
214                                                NaN        NaN
215                                                NaN        NaN
216                                                NaN        NaN
217                                                NaN        NaN
218                                                NaN        NaN
219                                                NaN        NaN

                                            Unnamed: 9     ...      \
0                                                  NaN     ...
1                                                  NaN     ...
2                                                  NaN     ...
3                                                  NaN     ...
4                                                  NaN     ...
5                                                  NaN     ...
6    Combined gross enrolment ratio for primary, se...     ...
7                                                  NaN     ...
8                                                  NaN     ...
9                                                  NaN     ...
10                                                95.4     ...
11                                                99.2     ...
12                                               113.0     ...
13                                                99.2     ...
14                                                99.9     ...
15                                                95.3     ...
16                                                85.7     ...
17                                                85.9     ...
18                                                98.4     ...
19                                                96.5     ...
20                                               101.0     ...
21                                                93.3     ...
22                                                98.0     ...
23                                               102.7     ...
24                                                91.9     ...
25                                                93.0     ...
26                                                95.1     ...
27                                                84.7     ...
28                                               108.4     ...
29                                                90.6     ...
..                                                 ...     ...
190                                               64.1     ...
191                                               47.8     ...
192                                               65.5     ...
193                                               69.4     ...
194                                               81.2     ...
195                                               60.3     ...
196                                               50.4     ...
197                                               83.5     ...
198                                               88.6     ...
199                                               93.5     ...
200                                                NaN     ...
201                                               88.4     ...
202                                               65.3     ...

#

# visuliation des 15  PREMIERES LIGNES

In [5]:

df.head(14)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Monitoring human development: enlarging people's choices . . .,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32
0,1 Human development index,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Table 1. Human development index,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,Human development index (HDI) value\n2005,NaN,Life expectancy at birth\n(years)\n2005,NaN,Adult literacy rate\n(% aged 15 and above)\n19...,NaN,"Combined gross enrolment ratio for primary, se...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,HDI ranka,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1,Iceland,NaN,0.968,NaN,81.5,NaN,..,d,95.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2,Norway,NaN,0.968,NaN,79.8,NaN,..,d,99.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,3,Australia,NaN,0.962,NaN,80.9,NaN,..,d,113.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,4,Canada,NaN,0.961,NaN,80.3,NaN,..,d,99.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df=pd.read_excel('table.xlsx',header=12)
df

,1,Iceland,Unnamed: 2,0.968,Unnamed: 4,81.5,Unnamed: 6,..,d,95.4,...,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32
0,2,Norway,NaN,0.968,NaN,79.8,NaN,..,d,99.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,Australia,NaN,0.962,NaN,80.9,NaN,..,d,113.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4,Canada,NaN,0.961,NaN,80.3,NaN,..,d,99.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,Ireland,NaN,0.959,NaN,78.4,NaN,..,d,99.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6,Sweden,NaN,0.956,NaN,80.5,NaN,..,d,95.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,7,Switzerland,NaN,0.955,NaN,81.3,NaN,..,d,85.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,8,Japan,NaN,0.953,NaN,82.3,NaN,..,d,85.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,9,Netherlands,NaN,0.953,NaN,79.2,NaN,..,d,98.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,10,France,NaN,0.952,NaN,80.2,NaN,..,d,96.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,11,Finland,NaN,0.952,NaN,78.9,NaN,..,d,101.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,12,United States,NaN,0.951,NaN,77.9,NaN,..,d,93.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,13,Spain,NaN,0.949,NaN,80.5,NaN,..,d,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,14,Denmark,NaN,0.949,NaN,77.9,NaN,..,d,102.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,15,Austria,NaN,0.948,NaN,79.4,NaN,..,d,91.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,16,United Kingdom,NaN,0.946,NaN,79.0,NaN,..,d,93.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,17,Belgium,NaN,0.946,NaN,78.8,NaN,..,d,95.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,18,Luxembourg,NaN,0.944,NaN,78.4,NaN,..,d,84.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,19,New Zealand,NaN,0.943,NaN,79.8,NaN,..,d,108.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,20,Italy,NaN,0.941,NaN,80.3,NaN,98.4,NaN,90.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,21,"Hong Kong, China (SAR)",NaN,0.937,NaN,81.9,NaN,..,j,76.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,22,Germany,NaN,0.935,NaN,79.1,NaN,..,d,88.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,23,Israel,NaN,0.932,NaN,80.3,NaN,97.1,k,89.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,24,Greece,NaN,0.926,NaN,78.9,NaN,96.0,NaN,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,25,Singapore,NaN,0.922,NaN,79.4,NaN,92.5,NaN,87.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,26,Korea (Republic of),NaN,0.921,NaN,77.9,NaN,..,d,96.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,27,Slovenia,NaN,0.917,NaN,77.4,NaN,99.7,"d,l",94.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,28,Cyprus,NaN,0.903,NaN,79.0,NaN,96.8,NaN,77.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,29,Portugal,NaN,0.897,NaN,77.7,NaN,93.8,l,89.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,30,Brunei Darussalam,NaN,0.894,NaN,76.7,NaN,92.7,NaN,77.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,31,Barbados,NaN,0.892,NaN,76.6,NaN,..,"d,j",88.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,Developing countries,NaN,NaN,0.691,NaN,66.1,NaN,76.6,NaN,64.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,Least developed countries,NaN,NaN,0.488,NaN,54.5,NaN,53.9,NaN,47.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181,Arab States,NaN,NaN,0.699,NaN,67.5,NaN,70.3,NaN,65.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,East Asia and the Pacific,NaN,NaN,0.771,NaN,71.7,NaN,90.7,NaN,69.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183,Latin America and the Caribbean,NaN,NaN,0.803,NaN,72.8,NaN,90.3,NaN,81.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
184,South Asia,NaN,NaN,0.611,NaN,63.8,NaN,59.5,NaN,60.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185,Sub-Saharan Africa,NaN,NaN,0.493,NaN,49.6,NaN,60.3,NaN,50.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
186,Central and Eastern Europe and the CIS,NaN,NaN,0.808,NaN,68.6,NaN,99.0,NaN,83.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187,OECD,NaN,NaN,0.916,NaN,78.3,NaN,..,NaN,88.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188,High-income OECD,NaN,NaN,0.947,NaN,79.4,NaN,..,NaN,93.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,High human development,NaN,NaN,0.897,NaN,76.2,NaN,..,NaN,88.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
191,Medium human development,NaN,NaN,0.698,NaN,67.5,NaN,78.0,NaN,65.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
192,Low human development,NaN,NaN,0.436,NaN,48.5,NaN,54.4,NaN,45.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,High income,NaN,NaN,0.936,NaN,79.2,NaN,..,NaN,92.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
195,Middle income,NaN,NaN,0.776,NaN,70.9,NaN,89.9,NaN,73.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,Low income,NaN,NaN,0.570,NaN,60.0,NaN,60.2,NaN,56.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,World,NaN,NaN,0.743,NaN,68.1,NaN,78.6,NaN,67.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,NOTES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,a. The HDI rank is determined using HDI values...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,SOURCES\nColumn 1: calculated on the basis of ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# SUPRESSION  DES  COLONNNES   VIDES

In [7]:
df=df.dropna(how="all",axis=1)

# SUPRESSION DES LIGNES  VIDES

In [8]:
df=df.dropna(how="all",axis=0)

# RENISIALISATION  DES 6 PREMIERES ENTETES

In [9]:
df= df.reset_index(drop=True)
df.head(6)

,1,Iceland,0.968,81.5,Unnamed: 6,..,d,95.4,e,"36,510",Unnamed: 12,0.941,0.978,0.985,4
0,2,Norway,0.968,79.8,NaN,..,d,99.2,NaN,"41,420",f,0.913,0.991,1.000,1
1,3,Australia,0.962,80.9,NaN,..,d,113.0,g,"31,794",NaN,0.931,0.993,0.962,13
2,4,Canada,0.961,80.3,NaN,..,d,99.2,"e,h","33,375",NaN,0.921,0.991,0.970,6
3,5,Ireland,0.959,78.4,NaN,..,d,99.9,NaN,"38,505",NaN,0.890,0.993,0.994,-1
4,6,Sweden,0.956,80.5,NaN,..,d,95.3,NaN,"32,525",NaN,0.925,0.978,0.965,7
5,7,Switzerland,0.955,81.3,NaN,..,d,85.7,NaN,"35,633",NaN,0.938,0.946,0.981,-1

# REDEFINITION  DES  VARIABLES(COLONNES)

In [10]:
columns =[]
for c in df.columns:
    columns.append([str(v) for v in df[c][0:1] if pd.notnull(v)])

print(columns)

[['2'], ['Norway'], ['0.968'], ['79.8'], [], ['..'], ['d'], ['99.2'], [], ['41,420'], ['f'], ['0.9129999999999999'], ['0.991'], ['1.0'], ['1']]

In [28]:
columns = ['HDI_rank','country','reference_1',
       'HDI_value',
       'reference_2', 'Life expectancy at birth', 'reference_3',
       'Adult literacy rate', 'reference_4',
       'Combined gross enrolment ratio for primary, secondary and tertiary education', 'reference_5',
       'GDP','reference_6',
          'Life expectancy index','reference_7']

In [29]:
df.columns =columns
df = df.drop(np.arange(1), axis=0).reset_index(drop=True)
df.head()

,HDI_rank,country,reference_1,HDI_value,reference_2,Life expectancy at birth,reference_3,Adult literacy rate,reference_4,"Combined gross enrolment ratio for primary, secondary and tertiary education",reference_5,GDP,reference_6,Life expectancy index,reference_7
0,3,Australia,0.962,80.9,NaN,..,d,113.0,g,"31,794",NaN,0.931,0.993,0.962,13
1,4,Canada,0.961,80.3,NaN,..,d,99.2,"e,h","33,375",NaN,0.921,0.991,0.970,6
2,5,Ireland,0.959,78.4,NaN,..,d,99.9,NaN,"38,505",NaN,0.890,0.993,0.994,-1
3,6,Sweden,0.956,80.5,NaN,..,d,95.3,NaN,"32,525",NaN,0.925,0.978,0.965,7
4,7,Switzerland,0.955,81.3,NaN,..,d,85.7,NaN,"35,633",NaN,0.938,0.946,0.981,-1

# AFFICHAGE DES 90 DERNIERS PAYS

In [30]:
df.tail(90)

,HDI_rank,country,reference_1,HDI_value,reference_2,Life expectancy at birth,reference_3,Adult literacy rate,reference_4,"Combined gross enrolment ratio for primary, secondary and tertiary education",reference_5,GDP,reference_6,Life expectancy index,reference_7
107,109,Turkmenistan,0.713,62.6,NaN,98.8,NaN,..,r,"3,838",h,0.627,0.903,0.609,5
108,110,Nicaragua,0.710,71.9,NaN,76.7,NaN,70.6,e,"3,674",n,0.782,0.747,0.601,6
109,111,Moldova,0.708,68.4,NaN,99.1,"d,l",69.7,e,"2,100",NaN,0.724,0.892,0.508,25
110,112,Egypt,0.708,70.7,NaN,71.4,NaN,76.9,e,"4,337",NaN,0.761,0.732,0.629,-1
111,113,Uzbekistan,0.702,66.8,NaN,..,"d,j",73.8,"e,h","2,063",NaN,0.696,0.906,0.505,25
112,114,Mongolia,0.700,65.9,NaN,97.8,NaN,77.4,NaN,"2,107",NaN,0.682,0.910,0.509,21
113,115,Honduras,0.700,69.4,NaN,80.0,NaN,71.2,e,"3,430",n,0.739,0.771,0.590,3
114,116,Kyrgyzstan,0.696,65.6,NaN,98.7,NaN,77.7,NaN,"1,927",NaN,0.676,0.917,0.494,29
115,117,Bolivia,0.695,64.7,NaN,86.7,NaN,86.0,"e,h","2,819",NaN,0.662,0.865,0.557,7
116,118,Guatemala,0.689,69.7,NaN,69.1,NaN,67.3,e,"4,568",n,0.746,0.685,0.638,-11
117,119,Gabon,0.677,56.2,NaN,84.0,l,72.4,"e,h","6,954",NaN,0.521,0.801,0.708,-35
118,120,Vanuatu,0.674,69.3,NaN,74.0,NaN,63.4,e,"3,225",n,0.738,0.705,0.580,2
119,121,South Africa,0.674,50.8,NaN,82.4,NaN,77.0,h,"11,110",n,0.430,0.806,0.786,-65
120,122,Tajikistan,0.673,66.3,NaN,99.5,d,70.8,NaN,"1,356",NaN,0.689,0.896,0.435,32
121,123,Sao Tome and Principe,0.654,64.9,NaN,84.9,NaN,65.2,NaN,"2,178",NaN,0.665,0.783,0.514,10
122,124,Botswana,0.654,48.1,NaN,81.2,NaN,69.5,e,"12,387",NaN,0.385,0.773,0.804,-70
123,125,Namibia,0.650,51.6,NaN,85.0,NaN,64.7,e,"7,586",n,0.444,0.783,0.723,-47
124,126,Morocco,0.646,70.4,NaN,52.3,NaN,58.5,e,"4,555",NaN,0.757,0.544,0.637,-18
125,127,Equatorial Guinea,0.642,50.4,NaN,87.0,NaN,58.1,"e,h","7,874","h,n",0.423,0.773,0.729,-54
126,128,India,0.619,63.7,NaN,61.0,NaN,63.8,e,"3,452",n,0.645,0.620,0.591,-11
127,129,Solomon Islands,0.602,63.0,NaN,76.6,k,47.6,NaN,"2,031",n,0.633,0.669,0.503,14
128,130,Lao People's Democratic Republic,0.601,63.2,NaN,68.7,NaN,61.5,NaN,"2,039",NaN,0.637,0.663,0.503,11
129,131,Cambodia,0.598,58.0,NaN,73.6,NaN,60.0,e,"2,727",n,0.550,0.691,0.552,-6
130,132,Myanmar,0.583,60.8,NaN,89.9,NaN,49.5,e,"1,027","h,y",0.596,0.764,0.389,35
131,133,Bhutan,0.579,64.7,NaN,47.0,v,..,r,..,"h,z",0.662,0.485,0.589,-14
132,134,Comoros,0.561,64.1,NaN,..,j,46.4,e,"1,993",n,0.651,0.533,0.499,10
133,135,Ghana,0.553,59.1,NaN,57.9,NaN,50.7,e,"2,480",n,0.568,0.555,0.536,-8
134,136,Pakistan,0.551,64.6,NaN,49.9,NaN,40.0,e,"2,370",NaN,0.659,0.466,0.528,-8
135,137,Mauritania,0.550,63.2,NaN,51.2,NaN,45.6,NaN,"2,234",n,0.637,0.493,0.519,-5
136,138,Lesotho,0.549,42.6,NaN,82.2,NaN,66.0,e,"3,335",n,0.293,0.768,0.585,-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,168,Congo (Democratic Republic of the),0.411,45.8,NaN,67.2,NaN,33.7,"e,h",714,n,0.346,0.560,0.328,7
168,169,Ethiopia,0.406,51.8,NaN,35.9,NaN,42.1,e,"1,055",n,0.446,0.380,0.393,-5
169,170,Chad,0.388,50.4,NaN,25.7,NaN,37.5,e,"1,427",n,0.423,0.296,0.444,-17
170,171,Central African Republic,0.384,43.7,NaN,48.6,NaN,29.8,"e,h","1,224",n,0.311,0.423,0.418,-13
171,172,Mozambique,0.384,42.8,NaN,38.7,NaN,52.9,NaN,"1,242",n,0.296,0.435,0.421,-16
172,173,Mali,0.380,53.1,NaN,24.0,NaN,36.7,NaN,"1,033",NaN,0.469,0.282,0.390,-8
173,174,Niger,0.374,55.8,NaN,28.7,NaN,22.7,NaN,781,n,0.513,0.267,0.343,-1
174,175,Guinea-Bissau,0.374,45.8,NaN,..,j,36.7,"e,h",827,n,0.347,0.421,0.353,-4
175,176,Burkina Faso,0.370,51.4,NaN,23.6,NaN,29.3,NaN,"1,213",n,0.440,0.255,0.417,-17
176,177,Sierra Leone,0.336,41.8,NaN,34.8,NaN,44.6,h,806,NaN,0.280,0.381,0.348,-5
177,Developing countries,NaN,0.691,66.1,NaN,76.6,NaN,64.1,NaN,"5,282",NaN,0.685,0.725,0.662,..
178,Least developed countries,NaN,0.488,54.5,NaN,53.9,NaN,47.8,NaN,"1,499",NaN,0.492,0.519,0.452,..
179,Arab States,NaN,0.699,67.5,NaN,70.3,NaN,65.5,NaN,"6,716",NaN,0.708,0.687,0.702,..
180,East Asia and the Pacific,NaN,0.771,71.7,NaN,90.7,NaN,69.4,NaN,"6,604",NaN,0.779,0.836,0.699,..
181,Latin America and the Caribbean,NaN,0.803,72.8,NaN,90.3,NaN,81.2,NaN,"8,417",NaN,0.797,0.873,0.740,..
182,South Asia,NaN,0.611,63.8,NaN,59.5,NaN,60.3,NaN,"3,416",NaN,0.646,0.598,0.589,..
183,Sub-Saharan Africa,NaN,0.493,49.6,NaN,60.3,NaN,50.4,NaN,"1,998",NaN,0.410,0.570,0.500,..
184,Central and Eastern Europe and the CIS,NaN,0.808,68.6,NaN,99.0,NaN,83.5,NaN,"9,527",NaN,0.726,0.938,0.761,..
185,OECD,NaN,0.916,78.3,NaN,..,NaN,88.6,NaN,"29,197",NaN,0.888,0.912,0.947,..
186,High-income OECD,NaN,0.947,79.4,NaN,..,NaN,93.5,NaN,"33,831",NaN,0.906,0.961,0.972,..
187,High human development,NaN,0.897,76.2,NaN,..,NaN,88.4,NaN,"23,986",NaN,0.854,0.922,0.915,..
188,Medium human development,NaN,0.698,67.5,NaN,78.0,NaN,65.3,NaN,"4,876",NaN,0.709,0.738,0.649,..
189,Low human development,NaN,0.436,48.5,NaN,54.4,NaN,45.5,NaN,"1,112",NaN,0.391,0.515,0.402,..
190,High income,NaN,0.936,79.2,NaN,..,NaN,92.3,NaN,"33,082",NaN,0.903,0.937,0.968,..
191,Middle income,NaN,0.776,70.9,NaN,89.9,NaN,73.3,NaN,"7,416",NaN,0.764,0.843,0.719,..
192,Low income,NaN,0.570,60.0,NaN,60.2,NaN,56.3,NaN,"2,531",NaN,0.583,0.589,0.539,..
193,World,NaN,0.743,68.1,NaN,78.6,NaN,67.8,NaN,"9,543",NaN,0.718,0.750,0.761,..
194,NOTES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
195,a. The HDI rank is determined using HDI values...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,SOURCES\nColumn 1: calculated on the basis of ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN